name: 'Deployment Feedback'
description: 'Continuous Deployment feedback for releases'
inputs:
  token:
    required: true
  repository:
    required: true
  ref:
    required: true
  clusterName:
    required: true
  serviceName:
    required: true
  releaseVersion:
    required: true
  devEcsKey:
    required: true
  devEcsSecret:
    required: true
  previewEcsKey:
    required: true
  previewEcsSecret:
    required: true
  productionEcsKey:
    required: true
  productionEcsSecret:
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
